//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ev
    {
        public ev()
        {
            this.satis = new HashSet<satis>();
        }
    
        public int ev_id { get; set; }
        public string adres { get; set; }
        public string isitma { get; set; }
        public Nullable<int> banyosayisi { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> kat { get; set; }
        public Nullable<int> odasayisi { get; set; }
        public string cephe { get; set; }
        public Nullable<int> metrekare { get; set; }
        public string durum { get; set; }
    
        public virtual ICollection<satis> satis { get; set; }
    }
}
