//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public musteri()
        {
            this.satis = new HashSet<satis>();
        }
    
        public string tckimlik { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public Nullable<int> yas { get; set; }
    
        public virtual ICollection<satis> satis { get; set; }
    }
}
