//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        public int satis_id { get; set; }
        public Nullable<int> ev_id { get; set; }
        public string tc_kimlik { get; set; }
    
        public virtual ev ev { get; set; }
        public virtual musteri musteri { get; set; }
    }
}
